modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"

[[mods]]
modId="unifiedmetrics"
version="${version}"
displayName="UnifiedMetrics"
authors="Cubxity"
description='''
Fully-featured metrics plugin for Minecraft servers
'''

displayURL="https://github.com/Cubxity/UnifiedMetrics/"
issueTrackerURL="https://github.com/Cubxity/UnifiedMetrics/issues"

[[dependencies.unifiedmetrics]]
modId="neoforge"
type="required"
versionRange="[21.1.215,)"
ordering="NONE"
side="SERVER"

[[dependencies.unifiedmetrics]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="SERVER"
